#!/usr/bin/env python

import pygtk
import gtk
#import os
import sys

class PasteImg:

    def __init__(self):
        clipb = gtk.clipboard_get()
        clipb.request_image(self.callback_img, sys.argv[1])

    def callback_img(self, clipboard, pixbuf, filename):
        imgType="png"
        if pixbuf is None:
            print "No image available!"
        else:
            print "Saving clipboard image to file(%s): %s" % (imgType, filename)
            pixbuf.save(filename, imgType)

        gtk.main_quit()
        
    def main(self):
        gtk.main()

if __name__ == "__main__":
    pimg = PasteImg()
    pimg.main()
